# basic info

__package_name__ = "SMOP"
__package_cmd__ = "smop"
__version__ = "0.5-beta"

# description

__desc__ = """SMOP stands for Small Matlab and Octave to Python compiler, it takes MATLAB
files and translates them to Python.  The names of the resulting files are derived 
from the names of the source files unless explicitly set with -o ."""

__example__ = """Example:
    $ wget ftp://ftp.gnu.org/gnu/octave/octave-4.0.2.tar.gz
    $ smop -a octave-4.0.2.tar.gz -g '*/scripts/*.m'
    $ ls -1 *.py | wc
    $ python -m py_compile *.py
    $ ls -1 *.pyc | wc"""
    
__desc_usage__ = "smop [OPTIONS] [FILE1.m FILE2.m ...]"
    
# generator
__header__ = f'Generated by SMOP v{__version__}'